routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use App\Mail\WelcomeMail;
// use Illuminate\Support\Facades\Mail;
// Route::get('/email', function () {
//     Mail::to('email@email.com')->send(new WelcomeMail());
//     return new WelcomeMail();
// });


Route::get('/', 'App\Http\Controllers\HomeController@index')->name('base');







Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');
Route::get('/blogs/{category_id}', 'App\Http\Controllers\PostController@viewBlogs')->name('view.blogs');

Route::get('/blogs','App\Http\Controllers\PostController@blogs')->name('blog.view');
Route::get('/about','App\Http\Controllers\PostController@about')->name('about.view');
Route::get('/singleBlog/{post_id}','App\Http\Controllers\PostController@singleBlog')->name('singleBlog.view');
Route::get('/destinations','App\Http\Controllers\PostController@destinations')->name('travelDestination.view');
Route::get('/elements','App\Http\Controllers\PostController@elements')->name('element.view');
Route::get('/contacts','App\Http\Controllers\PostController@contacts')->name('contact.view');
Route::get('/destinationDetails','App\Http\Controllers\PostController@destinationDetails')->name('destination.view');





// Route::any('posts.index',function(){
//     $q = Input::get ( 'q' );
//     $user = User::where('name','LIKE','%'.$q.'%')->orWhere('email','LIKE','%'.$q.'%')->get();
//     if(count($user) > 0)
//         return view('welcome')->withDetails($user)->withQuery ( $q );
//     else return view ('welcome')->withMessage('No Details found. Try to search again !');
// });

Route::post('/searchBlogs','App\Http\Controllers\PostController@searchBlogs')->name('blogs.search');



Auth::routes();

    Route::get('/admin', 'App\Http\Controllers\AdminController@admin')    
        ->middleware('is_admin')    
        ->name('admin');



Route::resource('categories','App\Http\Controllers\CategoryController') ->middleware('is_admin');
Route::resource('posts','App\Http\Controllers\PostController') ->middleware('is_admin');
Route::resource('tags','App\Http\Controllers\TagController') ->middleware('is_admin');
Route::resource('settings','App\Http\Controllers\SettingController') ->middleware('is_admin');
Route::resource('settings','App\Http\Controllers\SettingController') ->middleware('is_admin');
Route::resource('social_medias','App\Http\Controllers\SocialMediaController') ->middleware('is_admin');
Route::resource('testimonials','App\Http\Controllers\TestimonialController') ->middleware('is_admin');


Route::resource('subscribes','App\Http\Controllers\SubscribeController');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Post extends Model
{
    use HasFactory;
    use SoftDeletes;

    public function category(){
        return $this->belongsTo('App\Models\Category');
    }
    public function tags(){
        return $this->belongsToMany('App\Models\Tag', 'post_tag');
    }
    protected $fillable = [ 
        'title',       
        'description',              
        'image_name',  
        'image_url',
        'category_id',
        'tag_id'    
    ];
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;
use File;
use Illuminate\Http\Request;
use App\Models\Post;
use App\Models\Category;
use App\Models\Tag;



class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $posts = Post::all();
             
        return view('layouts.posts.index', compact('posts'));  

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories=Category::all();
        $tags=Tag::all();
        return view('layouts.posts.create',compact('categories','tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([            
             'title'=>'required',                     
            'description'=>'required', 
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048'

            ]);
           
            

            if ($request->hasFile('image')) {
                $image = $request->file('image');
                $image_name= time().'.'.$image->getClientOriginalExtension();
                $destinationPath = public_path('/images');
                $image->move($destinationPath, $image_name);  

            }


            $post = new Post([   
                'title'=> $request->get('title'),
                'description' => $request->get('description'),                        
                'image_name'=>$image_name,
               'image_url'=>$destinationPath 
       
           
                   
           ]);  

                   
           $category_id=$request->get('category_id');
           if($category_id==null){
           $post->save();
           }
           else{
            $category=Category::find($category_id);
            $category->posts()->save($post);
           } 
           $tag_ids=$request->get('tag_id');
          
           $post->tags()->attach($tag_ids);
           
           
      
           
       
          
           return redirect()->route('posts.index')->with('success', 'Post saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $post = Post::find($id);
        $category_id=$post->category_id;
        $category = Category::find($category_id);   
        $categories=Category::all(); 
        
        
        $tag_id=$post->tag_id;
        $tag = Tag::find($tag_id);   
        $tags=Tag::all(); 
       return view('layouts.posts.edit',compact('post','category','categories','tag','tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

        $request->validate([            
              'title'=>'required',                     
             'description'=>'required', 
             'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048'
                       
         ]);        
        

        $post=Post::find($id);
     File::delete(public_path("/images/").$post->image_name);  
    
    
         if ($request->hasFile('image')) {
             $image = $request->file('image');
             $image_name = time().'.'.$image->getClientOriginalExtension();
             $destinationPath = public_path('/images');
             $image->move($destinationPath, $image_name);
             
         }    
            $post->title=$request->get('title');
              $post->description=$request->get('description');                    
               $post->image_name=$image_name;
               $post->image_url=$destinationPath;
                $post->save();
          return redirect()->route('posts.index')->with('success', 'Post saved!');
          
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $post = Post::find($id); 
            
        $post->delete();        
        return redirect()->route('posts.index')->with('success', 'Post Deleted!');
    } 
    public function blogs(){

        $posts = Post::all();
        $categories=Category::all();
        $tags=Tag::all(); 
       
             
        return view('blog', compact('posts','categories','tags')); 


    }
    public function about(){

        $posts = Post::all();
             
        return view('about', compact('posts')); 


    }
    public function singleBlog($post_id){
        $post= Post::find($post_id);  
        
        $categories=Category::all();
        $tags=Tag::all();
             
        return view('single-blog', compact('post','categories','tags')); 


    }
    public function destinations(){

        $posts = Post::all();
             
        return view('travel_destination', compact('posts')); 


    }
    public function elements(){

        $posts = Post::all();
             
        return view('elements', compact('posts')); 


    }
    public function contacts(){

        $posts = Post::all();
             
        return view('contact', compact('posts')); 


    }
    public function destinationDetails(){

        $posts = Post::all();
             
        return view('destination_details', compact('posts')); 


    }

    public function searchBlogs(Request $request){
      $text= $request->get('search_text');

     
       

        $posts = Post::where( 'title', 'like', '%' . $text . '%')->get();

             
        $categories=Category::all();
             
        return view('blog', compact('posts','categories')); 


    }
    public function viewBlogs($category_id){
        $category = Category::find($category_id);  
       
        $posts= $category->posts;

        $categories=Category::all();
             
        return view('blog', compact('posts','categories')); 
       
    }
   

    



    
}

resources/views/layouts/posts/create.blade.php
@extends('home')
@section('homecontent')

<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
            <script>
            tinymce.init({
                selector: 'textarea',
                plugis:'link code',
                menubar: false

                });
            
            </script> 

<div class="row"> 
    <div class="col-sm-8 offset-sm-2">    
        <h3 class="display-4">Post</h3>  
        <div>    
            @if ($errors->any())      
            <div class="alert alert-danger">        
                <ul>            
                @foreach ($errors->all() as $error)              
                <li>{{ $error }}</li>            
                @endforeach        
                </ul>      
            </div>
            <br /> 

            
            @endif   

              
            <form enctype="multipart/form-data" method="post" action="{{ route('posts.store') }}">
             @csrf 
            
             <div class="form-group">                  
                <label for="title">title:</label>              
                <input type="text" class="form-control" name="title"/>          
            </div>

             <div class="form-group"> 
                            
                <label for="description">description:</label>              
                <textarea rows="5" cols="60"  name="description"> Enter the description here... </textarea>          
            </div>


            <div class="form-group d-flex flex-column">                  
                <label for="image">Image:</label>          
                <input type="file"  name="image"/>  
                       
            </div> 

                <div class="form-group">
                <label for="category_id">Select Category</label>
               
                <select name="category_id" class="form-control" id="category_id">
                @foreach($categories as $category)
                <option value="{{$category->id}}">{{$category->name}}</option>
               
                @endforeach
                
                
                </select>
                </div>
                <div class="form-group">
               
                <label for="tags">Choose Tag:</label>

                    <select name="tag_id[]" class="form-control" id="tag_id" multiple>
                    @foreach($tags as $tag)
                    <option value="{{$tag->id}}">{{$tag->type}}</option>
            @endforeach
            </select>
            </div>
           
             <button type="submit" class="btn btn-success">Save</button>
            <a href="{{ route('posts.index') }}" class="btn btn-primary">Cancel</a> 
               
            </form>  
        </div>
    </div>
</div>
@endsection 

resources/views/layouts/posts/edit.blade.php
@extends('home')
@section('homecontent')
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
            <script>
            tinymce.init({
                selector: 'textarea',
                plugis:'link code',
                menubar: false
                });
            
            </script> 
<div class="row">    
    <div class="col-sm-8 offset-sm-2">        
        <h3 class="display-4">Update Post</h3>        
        @if ($errors->any())        
        <div class="alert alert-danger">            
            <ul>                
            @foreach ($errors->all() as $error)                
            <li>{{ $error }}</li>                
            @endforeach            
            </ul>        
        </div>        
        <br />         
        @endif        
        <form enctype="multipart/form-data"  method="post" action="{{ route('posts.update', [$post->id, $category->id,$tag->id]) }}"> 
                        
        @method('PUT')             
        @csrf  
        
            <div class="form-group"> 
            <div class="form-group">                
                <label for="title">:</label>                
                <input type="text" class="form-control" name="title" value={{ $post->title }}/>  
            </div> 
        
                           
                        
            <div class="form-group"> 
                            
                            <label for="description">description:</label>              
                            <textarea rows="5" cols="60"  name="description" value={{ $post->description }}> Enter the description here... </textarea>          
                        </div> 
            <div class="form-group d-flex flex-column">                
                <label for="image">Image:</label>                
                <input type="file"  name="image" value={{ $post->image_name }}/>  
            </div>  
            <div class="form-group">
                <label for="category_id">Select Category</label>
               
                <select name="category_id" class="form-control" id="category_id">
                @foreach($categories as $category)
                <option value="{{$category->id}}">{{$category->name}}</option>
               
                @endforeach
                
                </select>
            </div>
            <div class="form-group d-flex flex-column">
               
                <label for="tag_id">Choose Tag:</label>

                    <select name="tag_id" class="form-control" id="tag_id" multiple>
                    @foreach($tags as $tag)
                    <option value="{{$tag->id}}">{{$tag->type}}</option>
            @endforeach
            </select>
            </div>
             <button type="submit" class="btn btn-success">Update</button>        
            <a href="{{ route('posts.index') }}" class="btn btn-primary">Cancel</a>                        
        </form>
    </div>
</div>
@endsection

resources/views/layouts/posts/index.blade.php
@extends('home')
@section('homecontent')
<div class="row">
    <div class="col-sm-12">    
        <h1 class="display-4">Post</h1>   
        <a href="{{ route('posts.create') }}" class="btn btn-primary">Add Post</a> 
        
        <table class="table table-striped">    
            <thead>        
            <tr>
            <td>Title</td>            
                <td>Description</td>          
                <td>Image</td>
                <td> Category</td>
                <td> Tag</td>
                
                <td colspan = 2>Actions</td>        
            </tr>    
            </thead>    
            <tbody>        
                @foreach($posts as $post)     

                 
                    <tr>            
                    <td>{{$post->title}}</td>      
                        <td>{!!$post->description!!}
                        <!-- <button onclick="description()" id="{{$post->id}}">Read more</button> -->
                  
                        
                        </td>
                        <td>{{$post->image_name}}
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#imageModal-{{$post->id}}">
                            View
                            </button></td>
                        <td>{{$post->category !==null?  $post->category->name :''}}</td>
                        <td>{{$post->tags !==null?  $post->tags->map(function ($tag) {
                        return collect($tag)->only(['type']);
                      })->pluck('type')->implode(','):''}}</td>
                        


                     
                        

                       
                         <td>                                      
                            <a href="{{ route('posts.edit',$post->id)}}" class="btn btn-primary">Edit Post</a>  
                                      
                        </td> 
                        <td>
                          <form action="{{ route('posts.destroy',$post->id)}}" method="post">                  
                                @csrf                  
                                @method('DELETE')                  
                                <button class="btn btn-danger" type="submit">Delete</button>                
                            </form>    
                                      
                        </td>  
                                   
                        
                    </tr>
                    <div class="modal fade" id="imageModal-{{$post->id}}" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Image</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body"> 
      <img src="{{ URL::to('/') }}/images/{{$post->image_name}}" width="100%">  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>         
                @endforeach    
            </tbody>  
        </table>


       
    <div>
</div>@endsection