routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use App\Mail\WelcomeMail;
// use Illuminate\Support\Facades\Mail;
// Route::get('/email', function () {
//     Mail::to('email@email.com')->send(new WelcomeMail());
//     return new WelcomeMail();
// });


Route::get('/', 'App\Http\Controllers\HomeController@index')->name('base');







Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');
Route::get('/blogs/{category_id}', 'App\Http\Controllers\PostController@viewBlogs')->name('view.blogs');

Route::get('/blogs','App\Http\Controllers\PostController@blogs')->name('blog.view');
Route::get('/about','App\Http\Controllers\PostController@about')->name('about.view');
Route::get('/singleBlog/{post_id}','App\Http\Controllers\PostController@singleBlog')->name('singleBlog.view');
Route::get('/destinations','App\Http\Controllers\PostController@destinations')->name('travelDestination.view');
Route::get('/elements','App\Http\Controllers\PostController@elements')->name('element.view');
Route::get('/contacts','App\Http\Controllers\PostController@contacts')->name('contact.view');
Route::get('/destinationDetails','App\Http\Controllers\PostController@destinationDetails')->name('destination.view');





// Route::any('posts.index',function(){
//     $q = Input::get ( 'q' );
//     $user = User::where('name','LIKE','%'.$q.'%')->orWhere('email','LIKE','%'.$q.'%')->get();
//     if(count($user) > 0)
//         return view('welcome')->withDetails($user)->withQuery ( $q );
//     else return view ('welcome')->withMessage('No Details found. Try to search again !');
// });

Route::post('/searchBlogs','App\Http\Controllers\PostController@searchBlogs')->name('blogs.search');



Auth::routes();

    Route::get('/admin', 'App\Http\Controllers\AdminController@admin')    
        ->middleware('is_admin')    
        ->name('admin');



Route::resource('categories','App\Http\Controllers\CategoryController') ->middleware('is_admin');
Route::resource('posts','App\Http\Controllers\PostController') ->middleware('is_admin');
Route::resource('tags','App\Http\Controllers\TagController') ->middleware('is_admin');
Route::resource('settings','App\Http\Controllers\SettingController') ->middleware('is_admin');
Route::resource('settings','App\Http\Controllers\SettingController') ->middleware('is_admin');
Route::resource('social_medias','App\Http\Controllers\SocialMediaController') ->middleware('is_admin');
Route::resource('testimonials','App\Http\Controllers\TestimonialController') ->middleware('is_admin');


Route::resource('subscribes','App\Http\Controllers\SubscribeController');

app/Models/SocialMedia.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SocialMedia extends Model
{
   
    public $table = 'social_medias';
   
    use HasFactory;
  
    protected $fillable = [ 
        'name',
        'link',
        'icon'
       
           
    ];
    
}

app/Http/Controllers/SocialMediaController.php
<?php

namespace App\Http\Controllers;
use DB;
use Illuminate\Http\Request;
use App\Models\SocialMedia;

class SocialMediaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $social_medias=SocialMedia::all();
             
        return view('layouts.socialmedias.index', compact('social_medias')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $social_medias= SocialMedia::all();
             
        return view('layouts.socialmedias.create', compact('social_medias'));  
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([   
            'name'=>'required',         
            'link'=>'required', 
            'icon'=>'required'
            

           
           

           ]);


           $social_media = new SocialMedia([   
            'name'=>$request->get('name'), 
            'link'=> $request->get('link'),
            'icon'=> $request->get('icon'),
           
                                  
            
       ]);  
       $social_media->save();
       return redirect()->route('social_medias.index')->with('success', 'SocialMedia saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $social_media= SocialMedia::find($id);
        return view('layouts.socialmedias.edit', compact('social_media'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

        $request->validate([    
            'name'=>'required',        
            'link'=>'required', 
              'icon'=>'required'                 
               
       ]); 
       $social_media=SocialMedia::find($id);

       $social_media->name=$request->get('name');
       $social_media->link=$request->get('link');  
       $social_media->icon=$request->get('icon');  
     
       $social_media->save();
       return redirect()->route('social_medias.index')->with('success', 'SocialMedia saved!');  
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //

        $social_media = SocialMedia::find($id); 
            
        $social_media->delete();        
        return redirect()->route('social_medias.index')->with('success', 'SocialMedia Deleted!');
    }
}

resources/views/layouts/socialmedias/create.blade.php
@extends('home')
@section('homecontent')



<div class="row"> 
    <div class="col-sm-8 offset-sm-2">    
        <h3 class="display-4">Social Media</h3>  
        <div>    
            @if ($errors->any())      
            <div class="alert alert-danger">        
                <ul>            
                @foreach ($errors->all() as $error)              
                <li>{{ $error }}</li>            
                @endforeach        
                </ul>      
            </div>
            <br /> 

            
            @endif   

              
            <form enctype="multipart/form-data" method="post" action="{{ route('social_medias.store') }}">
             @csrf 
            
             <div class="form-group">
                <label for="socialMedia_id">Select Social Media</label>
               
                <select name="name" class="form-control">
                
                <option value="facebook">Facebook</option>
                <option value="instagram">Instagram</option>
                <option value="linkedin">Linkedin</option>
                <option value="google">Google</option>
           
                </select>
                </div>
            <div class="form-group">                  
                <label for="link">Link:</label>              
                <input type="text" class="form-control" name="link"/>          
            </div>
            <div class="form-group">
                <label for="socialMedia_id">Select Icon</label>
               
                <select name="icon" class="form-control">
                
                <option value="fa fa-facebook">facebook</option>
                <option value="fa fa-instagram">instagram</i></option>
                <option value="fa fa-linkedin">linkedin</option>
                <option value="fa fa-google">google</option>
           
                </select>
                </div>
                
            

            

           
             <button type="submit" class="btn btn-success">Save</button>
            <a href="{{ route('social_medias.index') }}" class="btn btn-primary">Cancel</a> 
               
            </form>  
        </div>
    </div>
</div>
@endsection 

resources/views/layouts/socialmedias/edit.blade.php
@extends('home')
@section('homecontent')
 
<div class="row">    
    <div class="col-sm-8 offset-sm-2">        
        <h3 class="display-4">Update Social Media</h3>        
        @if ($errors->any())        
        <div class="alert alert-danger">            
            <ul>                
            @foreach ($errors->all() as $error)                
            <li>{{ $error }}</li>                
            @endforeach            
            </ul>        
        </div>        
        <br />         
        @endif        
        <form method="post" action="{{ route('social_medias.update',$social_media->id) }}"> 
                        
        @method('PUT')             
        @csrf  
        
        <div class="form-group">
                <label for="socialMedia_id">Select Social Media</label>
               
                <select name="name" class="form-control">
                
                <option value="facebook">Facebook</option>
                <option value="instagram">Instagram</option>
                <option value="linkedin">Linkedin</option>
                <option value="google">Google</option>
           
                </select>
                </div>  
        <div class="form-group">                
                <label for="link">Link:</label>                
                <input type="text" class="form-control" name="link" value={{ $social_media->link}} />            
            </div> 
            <div class="form-group">
                <label for="socialMedia_id">Select Icon</label>
               
                <select name="icon" class="form-control">
                
                <option value="fa fa-facebook">facebook</option>
                <option value="fa fa-instagram">instagram</i></option>
                <option value="fa fa-linkedin">linkedin</option>
                <option value="fa fa-google">google</option>
           
                </select>
                </div>
             <button type="submit" class="btn btn-success">Update</button>        
            <a href="{{ route('social_medias.index') }}" class="btn btn-primary">Cancel</a>                        
        </form>
    </div>
</div>
@endsection

resources/views/layouts/socialmedias/index.blade.php
@extends('home')
@section('homecontent')
<div class="row">
    <div class="col-sm-12">    
        <h1 class="display-4">Social Media</h1>   
        <a href="{{ route('social_medias.create') }}" class="btn btn-primary">Add Social Media</a> 
       
        <table class="table table-striped">    
            <thead>        
            <tr>
            <td>Name</td>   
            <td>Link</td> 
            <td>icon</td>   
                
                
                
                <td colspan = 2>Actions</td>        
            </tr>    
            </thead>    
            <tbody>        
                @foreach($social_medias as $socialmedia)     

                 
                    <tr>            
                    <td>{{$socialmedia->name}}</td>   
                    <td>{{$socialmedia->link}}</td> 
                    <td>{{$socialmedia->icon}}</td>     
                                        
                        
                  
                        
                       
                       
                         <td>                                      
                            <a href="{{ route('social_medias.edit',$socialmedia->id)}}" class="btn btn-primary">Edit Social Media</a>  
                                      
                        </td> 
                        <td>
                          <form action="{{ route('social_medias.destroy',$socialmedia->id)}}" method="post">                  
                                @csrf                  
                                @method('DELETE')                  
                                <button class="btn btn-danger" type="submit">Delete</button>                
                            </form>    
                                      
                        </td>  
                                   
                        
                    </tr>
                    @endforeach  
                  
            </tbody>  
        </table>


       
    <div>
</div>@endsection