routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use App\Mail\WelcomeMail;
// use Illuminate\Support\Facades\Mail;
// Route::get('/email', function () {
//     Mail::to('email@email.com')->send(new WelcomeMail());
//     return new WelcomeMail();
// });


Route::get('/', 'App\Http\Controllers\HomeController@index')->name('base');







Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');
Route::get('/blogs/{category_id}', 'App\Http\Controllers\PostController@viewBlogs')->name('view.blogs');

Route::get('/blogs','App\Http\Controllers\PostController@blogs')->name('blog.view');
Route::get('/about','App\Http\Controllers\PostController@about')->name('about.view');
Route::get('/singleBlog/{post_id}','App\Http\Controllers\PostController@singleBlog')->name('singleBlog.view');
Route::get('/destinations','App\Http\Controllers\PostController@destinations')->name('travelDestination.view');
Route::get('/elements','App\Http\Controllers\PostController@elements')->name('element.view');
Route::get('/contacts','App\Http\Controllers\PostController@contacts')->name('contact.view');
Route::get('/destinationDetails','App\Http\Controllers\PostController@destinationDetails')->name('destination.view');





// Route::any('posts.index',function(){
//     $q = Input::get ( 'q' );
//     $user = User::where('name','LIKE','%'.$q.'%')->orWhere('email','LIKE','%'.$q.'%')->get();
//     if(count($user) > 0)
//         return view('welcome')->withDetails($user)->withQuery ( $q );
//     else return view ('welcome')->withMessage('No Details found. Try to search again !');
// });

Route::post('/searchBlogs','App\Http\Controllers\PostController@searchBlogs')->name('blogs.search');



Auth::routes();

    Route::get('/admin', 'App\Http\Controllers\AdminController@admin')    
        ->middleware('is_admin')    
        ->name('admin');



Route::resource('categories','App\Http\Controllers\CategoryController') ->middleware('is_admin');
Route::resource('posts','App\Http\Controllers\PostController') ->middleware('is_admin');
Route::resource('tags','App\Http\Controllers\TagController') ->middleware('is_admin');
Route::resource('settings','App\Http\Controllers\SettingController') ->middleware('is_admin');
Route::resource('settings','App\Http\Controllers\SettingController') ->middleware('is_admin');
Route::resource('social_medias','App\Http\Controllers\SocialMediaController') ->middleware('is_admin');
Route::resource('testimonials','App\Http\Controllers\TestimonialController') ->middleware('is_admin');


Route::resource('subscribes','App\Http\Controllers\SubscribeController');

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;
    public function childs(){
        return $this->hasMany('App\Models\Setting','parent_id','id');
    }


    protected $fillable = [ 
        'type', 
        'title',      
                     
        'route',  
        'parent_id'
           
    ];
}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Setting;
use view;

class SettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $settings = Setting::all();
             
        return view('settings.index', compact('settings'));  
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $settings = Setting::all();
             
        return view('settings.create', compact('settings'));  
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([   
            'type'=>'required',         
            'title'=>'required', 
            'route',
            'parent_id'

           
           

           ]);


           $setting = new Setting([   
            'type'=>$request->get('type'), 
            'title'=> $request->get('title'),
            'route'=>$request->get('route'),
            'parent_id'=>$request->get('parent_id')
                                  
            
       ]);  
       $setting->save();
       return redirect()->route('settings.index')->with('success', 'Setting saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $setting= Setting::find($id);
        return view('settings.edit', compact('setting'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

        $request->validate([    
            'type'=>'required',        
            'title'=>'required', 
            'route',
            'parent_id'                    
               
       ]); 
       $setting=Setting::find($id);

       $setting->type=$request->get('type');
       $setting->title=$request->get('title');  
      $setting->route=$request->get('route');
      $setting->parent_id=$request->get('parent_id');
       $setting->save();
       return redirect()->route('settings.index')->with('success', 'Setting saved!');  
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $setting = Setting::find($id); 
            
        $setting->delete();        
        return redirect()->route('settings.index')->with('success', 'Setting Deleted!');
    }
}

resources/views/settings/create.blade.php
@extends('home')
@section('homecontent')
<div class="row"> 
    <div class="col-sm-8 offset-sm-2">    
        <h3 class="display-4">Add Setting</h3>  
        <div>    
            @if ($errors->any())      
            <div class="alert alert-danger">        
                <ul>            
                @foreach ($errors->all() as $error)              
                <li>{{ $error }}</li>            
                @endforeach        
                </ul>      
            </div>
            <br />    
            @endif      
            <form enctype="multipart/form-data" method="post" action="{{ route('settings.store') }}">          
            @csrf 
            <div class="form-group">
                <label for="type">Select Type</label>
               
                <select name="type" class="form-control" >
               
                <option value="header">header</option>
              
                </select>
                </div>
            
             
            <div class="form-group d-flex flex-column">                  
                <label for="title">Title:</label>          
                <input type="text"  name="title"/>  
                       
            </div> 
            
            
            <!-- <div class="form-group d-flex flex-column">                  
                <label for="route">Route:</label>          
                <input type="text"  name="route"/>  
                       
            </div> -->
            <div class="form-group">
                <label for="parent_id">Select Route</label>
               
                <select name="route" class="form-control">
                
                <option value="home">home</option>
                <option value="about.view">about</option>
                <option value="travelDestination.view">travel destination</option>
                <option value="destination.view">destination</option>
                <option value="element.view">element</option>
                <option value="blog.view">blog</option>
                <option value="contact.view">contact</option>
               
                
                
                
                </select>
            </div>
           
            <div class="form-group">
                <label for="parent_id">Select Parent</label>
               
                <select name="parent_id" class="form-control" id="parent_id">
               <option value="">select</option>
                @foreach($settings as $setting)
                <option value="{{$setting->id}}">{{$setting->title}}</option>
               
                @endforeach
                
                
                </select>
            </div>
                  
                           
            <button type="submit" class="btn btn-success">Save</button>
            <a href="{{ route('settings.index') }}" class="btn btn-primary">Cancel</a>  
                
            </form>  
        </div>
    </div>
</div>
@endsection

resources/views/settings/edit.blade.php
@extends('home')
@section('homecontent')
<div class="row">    
    <div class="col-sm-8 offset-sm-2">        
        <h3 class="display-4">Update Setting</h3>        
        @if ($errors->any())        
        <div class="alert alert-danger">            
            <ul>                
            @foreach ($errors->all() as $error)                
            <li>{{ $error }}</li>                
            @endforeach            
            </ul>        
        </div>        
        <br />         
        @endif        
        <form enctype="multipart/form-data" method="post" action="{{ route('settings.update',$setting->id) }}">            
        @method('PATCH')             
        @csrf  

                  
        <div class="form-group">
                <label for="type">Select Type</label>
               
                <select name="type" class="form-control" >
               
                <option value="header">header</option>
               
              
                
                
                </select>
                </div> 
            <div class="form-group d-flex flex-column">                  
                <label for="title">Title:</label>          
                <input type="text"  name="title" value={{$setting->title}}/>  
                       
            </div> 
           
            
            <div class="form-group">
                <label for="parent_id">Select Route</label>
               
                <select name="route" class="form-control">
                
                <option value="home">home</option>
                <option value="about.view">about</option>
                <option value="travelDestination.view">travel destination</option>
                <option value="destination.view">destination</option>
                <option value="element.view">element</option>
                <option value="blog.view">blog</option>
                <option value="contact.view">contact</option>
               
               
                </select>
            </div>
            <div class="form-group">
                <label for="parent_id">Select Parent</label>
               
                <select name="parent_id" class="form-control" id="parent_id">
               <option value="">select</option>
                @foreach($settings as $setting)
                <option value="{{$setting->id}}">{{$setting->title}}</option>
               
                @endforeach
                
                
                </select>
            </div>
                  
           

            <button type="submit" class="btn btn-success">Update</button>        
            <a href="{{ route('categories.index') }}" class="btn btn-primary">Cancel</a>                        
        </form>
    </div>
</div>
@endsection

resources/views/settings/index.blade.php
@extends('home')
@section('homecontent')

<div class="row">
    <div class="col-sm-12">    
        <h1 class="display-4">Setting</h1>   
        <a href="{{ route('settings.create') }}" class="btn btn-primary">Add</a>  
        <table class="table table-striped">    
            <thead>        
            <tr>          
                <!-- <td> Category ID</td>           -->
                <td>Type</td>
                <td>Title</td>
               
                <td>Route</td>
                <td>Parent ID</td>
               

                <td colspan = 2>Actions</td>        
            </tr>    
            </thead>    
            <tbody>        
                @foreach($settings as $setting)        
                    <tr>            
                       
                        <td>{{$setting->type}}</td>
                        <td>{{$setting->title}} </td>
                       
                        <td>{{$setting->route}} </td>
                        <td>{{$setting->parent_id}}</td>
                        
                       
                        
                        
                        <td>                                      
                            <a href="{{ route('settings.edit',$setting->id)}}" class="btn btn-primary">Edit Setting</a>
                                                                  

                        </td> 
                        
                        
                        
                        <td>
                          <form action="{{ route('settings.destroy',$setting->id)}}" method="post">                  
                                @csrf                  
                               @method('DELETE')                  
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>    
                                      
                        </td> 
                        
          
                        
                    </tr>  




           





                @endforeach    
            </tbody>  
        </table>
    <div>
</div>@endsection